### ISSUE TITLE
Root directory of images

### ISSUE THREAD

**Issue by simongeek** [arturml/pytorch-unet#1]
How to change root to images in FishDataset.py (33-35 lines) if I have:
dataset/images/Img1.png...Img2.png etc.
dataset/mask/ImgMask1.png...ImgMask2.png etc.

Do you know how to do it?

**Comment by arturml** [comment]
Maybe something like this:

```python
class MyDataset(Dataset):
    def __init__(self, transform=None):
        self.transform = transform
        self.images = glob('dataset/images/*.png')
        self.masks = glob('dataset/mask/*.png')
        # sort to make sure imgs and masks are in the same order
        self.images.sort()
        self.masks.sort()
        # now you can shuffle them if you want
```
If you don't care about labels, your `__getitem__` function can return a pair `(image, mask)` only

**Comment by simongeek** [comment]
Then I got error:
`TypeError: __init__() got multiple values for argument 'transform'`

You know how to solve it?

**Comment by simongeek** [comment]
Ok, I solved this problem using another option. This issue can be closed. Thanks!
